### ISSUE TITLE
html5 audio with m4a files not playing [!http-kit was the problem]

### ISSUE THREAD

**Issue by sova** [patosai/ring-range-middleware#1]
[note: edited since original posting]

Hi and thank you very much for putting your efforts into this middleware!

I have just added it to my server, I don't know if it's a problem with [mobile and desktop] Safari, or if I am not doing something right.

I try loading the page in Safari with an .m4a file in an html5 <audio> element.  The page loads, the play button appears, but when I hit play nothing happens.  The response header seems OK...

```
Request
GET /members/lesson-2-page-0.m4a HTTP/1.1
Cookie: ring-session=747a0e85-91e6-47f6-ba9a-bc679f800bd8
Accept: */*
Connection: keep-alive
Range: bytes=0-1
Host: (redacted)
Accept-Language: en-us
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15
Referer: (redacted)
Accept-Encoding: identity
X-Playback-Session-Id: 6BFF011A-E243-4036-90AC-AE400FBCB84C

Response
HTTP/1.1 206 Partial Content
Content-Type: application/octet-stream
Keep-Alive: timeout=5, max=100
Last-Modified: Thu, 19 Nov 2020 18:56:41 GMT
X-XSS-Protection: 1; mode=block
Date: Thu, 03 Dec 2020 21:22:48 GMT
Content-Length: 288
Connection: Keep-Alive
X-Content-Type-Options: nosniff
Accept-Ranges: bytes
Content-Range: bytes 0-1/3530289
X-Frame-Options: SAMEORIGIN
Server: http-kit
```

There are 2 buttons on the audio controls: jump forward 15 seconds, and jump back 15 seconds, but when I hit them I get a `IndexSizeError: The index is not in the allowed range.`

Attempting to look at the Network>Other> and then the specific item .m4a > "Preview" says `An error occurred trying to load the resource.`

I really appreciate your efforts, I hope we can get to the bottom of this.

**Comment by patosai** [comment]
I did some searching around Safari and m4a, it might be that Safari is looking at the Content-Type which should be `audio/x-m4a` for m4a? Some other people have also reported that making the URL absolute other than relative works, or setting "type" inside the "source" like in this post: https://stackoverflow.com/a/63551862.

**Comment by patosai** [comment]
Looked at your edited response, this seems a bit off:
```
Content-Length: 288
Content-Range: bytes 0-1/3530289
```
Will look later tonight

**Comment by sova** [comment]
Yeah!  That could be it.  Please take a look.  Firefox doesn't complain but Safari won't even preview the file... hmmm

**Comment by patosai** [comment]
I got a random .m4a from the Internet and tried it on Safari 14.0.1 on v0.1.0 of this middleware and v1.8.2 of ring, and it worked with the Content-Type as both "audio/mp4" or "application/octet-stream" (didn't try others). Here is the HTML:

```html
<html>
<body>
  <audio controls>
    <source src="http://localhost:3000/test/assets/sample1.m4a">
  </audio>
  </body>
</html>
```

The content lengths were correct as well. Do you have some other middleware going on?

**Comment by sova** [comment]
Well that's really good to hear!  I do have other middleware at play...

`(wrap-session)` and `(wrap-defaults)`

Here's code that is running the server:

```
(-> all-the-routes
		(wrap-defaults site-defaults)
		(wrap-session {:store (cookie-store) :cookie-attrs {:max-age 234000000}})
		(range-middleware/wrap-range-header)
		(reload/wrap-reload)
		(server/run-server {:port 8887}))
```


And for the file dispatch (since they are behind authorized access)
```  
  (GET "/members/:filename" [filename :as r]
    (response/resource-response (str "members/" filename)))
```

Maybe you can detect something awry?

Edit2: I was checking Firefox > the Network tab in Inspector...
Turns out it is also not working in Firefox for me, I was using a cached copy for what I thought was working.
The actual result looks like this:  and the content-lengths are still not correct (all reading 300 or so)

![Screen Shot 2020-12-03 at 9 48 39 PM](https://user-images.githubusercontent.com/451489/101123196-86ae8580-35b1-11eb-9d17-2fe7c1b1b62c.png)

I don't understand why the Content-Length is not coming across correctly.  Is this because I'm using `resource-response` ?

**Comment by patosai** [comment]
Are you using Ring core/servlet/jetty adapter version >=1.6.0?

**Comment by sova** [comment]
Just upgraded ring-core to 1.8.2

Here's the relevant dependencies from my project.clj

```
[org.clojure/clojure "1.10.0"]
[org.clojure/clojurescript "1.10.520"]
[rum "0.11.3"]
[http-kit "2.3.0"]
[ring/ring-core "1.8.2"]
[ring/ring-defaults "0.3.2"]
[ring/ring-anti-forgery "1.0.0"]
[ring/ring-devel "1.8.0"]
[ring-range-middleware "0.1.0"]
```

Seems OK to me but maybe there is something out of date

**Comment by patosai** [comment]
How are you sending the body to the client?

**Comment by sova** [comment]
I added "content-type" "audio/x-m4a" to the resource-response.   
I'm not sure what you mean about how I'm sending the body, 
it's a resource-response to a GET request.
Could you please clarify?

```
(GET "/members/:filename" [filename :as r]
	(response/content-type 
	 (response/resource-response (str "members/" filename)) "audio/x-m4a"))
```

**Comment by patosai** [comment]
At the end of all your middleware, there's some server that sends the response to the client. If you're using the ring jetty adapter, which it doesn't seem like you are, it will automatically call `write-body-to-stream` on the body to send it to the client. The magic that this middleware does is hidden behind `write-body-to-stream` so that needs to be called.

What web server are you using?

**Comment by patosai** [comment]
Also you can manually call `curl -H "Range: bytes=0-1" http://your-url-here` to see what the server is actually returning

**Comment by sova** [comment]
Ohh I see I'm using http-kit.  The function wrapping the routes `(server/run-server ...)` is `[org.httpkit.server :as  server]`

**Comment by sova** [comment]
Aha.  The requests are returning HTML that reads the resource has moved ;/

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="(redacted)/audio-file.m4a">here</a>.</p>
<hr>
<address>Apache/2.4.7 (Ubuntu) Server at (redacted) Port 80</address>
</body></html>
```
Which, when saved to a file, is ~319B.

So it looks like the file is not actually getting served, it's just giving this text/html response...
I really appreciate your help, does this appear to be something fuzzy with http-kit?  Would it be better to rely on the jetty adapter?

**Comment by patosai** [comment]
I took a look at the source of httpkit and they seem to have issues supporting streaming, so you have a few options:

- use the Ring servlet with another Java server, but you'll need to rewrite your routing
- use the Ring jetty adapter and be done, but again rewrite your routing
- continue using the httpkit server, but write a wrapper around this middleware that calls `write-body-to-stream` and buffers the whole thing in memory, and replaces the body with the bytes. not recommended.
- use nginx or some other kind of reverse proxy in front of your httpkit server that handles all the static files - nginx has Range support built in and is probably faster. this may be the best solution for you, if you are ok with running another process.

**Comment by sova** [comment]
You are a rockstar!!!
Let's see... I was looking at X-Sendfile (for Apache), I'm not certain how to get it going though.
Ring Jetty Adapter sounds like the easiest fix.  What would need to change in the routing, if you have some pointers off the top of your head?

**Comment by patosai** [comment]
I've used https://github.com/juxt/bidi before, and that's pretty good for routing

**Comment by sova** [comment]
You're the man, man!

Switched my project.clj ring splinters to `[ring "1.8.2"]`
And then in the server `[ring.adapter.jetty :refer [run-jetty]]`  (not ring.jetty.adapter as I mis-read many times this morning xD!)

And simply replaced `server/run-server` with `run-jetty`

Flippin' SOLVED

**Comment by patosai** [comment]
Awesome 👍
